### ISSUE TITLE
GTDB RS220, any plans on updating?

### ISSUE THREAD

**Issue by julianzaugg** [biocore/greengenes2#10]
Hi,

The latest release for the GTDB (Release 09-RS220) has just been made available. Do you have any plans on updating GreenGenes2 to match this release in the near future?

As per an earlier issue https://github.com/biocore/greengenes2/issues/4, I assume you are still working on the taxonomy integration?

EDIT—Also, any plans on incorporating Eukaryotes?

Thanks!

**Comment by wasade** [comment]
Hi @julianzaugg, yes it is the plan. And I would love to include eukaryotes

Best,
Daniel

**Comment by wasade** [comment]
Closing as 2024.09 is released and based on R220. 

Eukaryotes are a future target.
