### ISSUE TITLE
Sequence mapping information

### ISSUE THREAD

**Issue by ygouin** [biocore/greengenes2#2]
Is there a way to get mapping/coordinate information about where the sequences are from?

**Comment by wasade** [comment]
Thanks, @ygouin! It the exact answer depends on the type of record. For the current release, we source data from:

- 16S rRNA from the [Living Tree Project](https://imedea.uib-csic.es/mmg/ltp/ltp-2022/) which uses accessions relative to Genbank (e.g., [`X80994`](https://www.ncbi.nlm.nih.gov/nuccore/X80994))
- 16S rRNA [GTDB](gtdb.ecogenomic.org/) which uses accessions similar to `GB-GCA-003856275.1-RQSQ01000048.1` (though note we replace `_` with `-`)
- 16S rRNA from the [Web of Life](https://biocore.github.io/wol/), which uses accessions like `G001820395` 
- 16S rRNA from [Karst et al 2021](https://www.nature.com/articles/s41592-020-01041-y) and [Shaffer et al 2022](https://www.nature.com/articles/s41564-022-01266-x). The full operons for these data are in [Qiita](https://qiita.ucsd.edu) under studies 10317 and 13114 respectively. These records look like `MJ010-2-barcode60-umi1554bins-ubs-138`. 

All of those full length 16S are in the publicly available backbone [artifact](https://ftp.microbio.me/greengenes_release/2022.10/2022.10.backbone.full-length.fna.qza). 

We additionally place 16S V4 fragments, and some full length records from [SILVA](https://www.arb-silva.de/) separately. The 16S fragments come from Qiita, as obtained by [redbiom](https://github.com/biocore/redbiom/). Those IDs are represented in three ways, either by ASV (e.g., `TACAGAACCCCCGAGCGTTACCCGGATTTATTGGGCGTAAAGGGTCTGTAGGTGGTCACGTAAGTTTCAAGTTAAAGCTCTTCGGCTTAA`), by MD5 (e.g., `48700b14c9d20c30b0f575d3e01e0e5c`) or by an arbitrary 8-digit identifier (e.g., `22383138`). The SILVA records retain their original ID (e.g., `JQIO01000430.1097739.1099039`)

With regards to coordinates, it depends on the exact data being considered. For the ASVs for example, they are all expected to be 16S V4, with many (hopefull all!) starting at 515F but samples included depend on accurate information from depositors. For the operons, I likely have the coordinates but would need to track them down -- I can do so if helpful. For LTP and GTDB, we use what is provided as is. For WoL, I think coordinates are provided in that resource but again I may be able to track down if needed.

I think that covers it. Please let me know if there are further questions!
