### ISSUE TITLE
GTDB release 214

### ISSUE THREAD

**Issue by danpal96** [biocore/greengenes2#4]
I think that the taxonomy is based on GTDB release 207, are there plans to update to the release 214 with the new phylum names?

**Comment by wasade** [comment]
Hi @danpal96, yes and I'm currently working hard on the taxonomy integration. The existing approach we took integrating LTP and GTDB is unlikely to work as these changes break some prior assumptions.

**Comment by wasade** [comment]
Hi @danpal96, we just released 2024.09 which is based on GTDB R220. Please see the post [here](https://forum.qiime2.org/t/greengenes2-2024-09/31606)
