### ISSUE TITLE
Using GreenGenes2 as Kraken 2 DB.

### ISSUE THREAD

**Issue by VoronDM** [biocore/greengenes2#6]
Until the major update of GreenGenes to GreenGenes2, it can be easily used as a custom 16S database for Kraken 2. To create such  database, only two files was needed - `${GG_VERSION}.fasta.gz` and `${GG_VERSION}_taxonomy.txt.gz`. This will be implemented as a simple bash script (https://github.com/DerrickWood/kraken2/blob/master/scripts/16S_gg_installation.sh). Since after a major update the structure of the GG2 database has changed, it is now not clear how it can be used with the Kraken2. 
Is it possible to implement a database compatible with the previous format?

**Comment by wasade** [comment]
Hi @VoronDM, it sounds like the kraken2 support script itself needs to be updated. I recommend opening an issue with that project. I'm not familiar with the script, but I would imagine it would need to use the backbone fasta and tax files available in the release

**Comment by wasade** [comment]
...@VoronDM, if you open an issue with that project, could you please tag me so I can coordinate with them?
